<template>
  <Head>
    <Title>nuxt-api-party</Title>
    <Link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css" />
  </Head>

  <header>
    <h1>nuxt-api-party</h1>
    <p>
      Requests are proxied by a Nuxt server route and passed back to the client. The playground uses <a href="https://jsonplaceholder.typicode.com/">{JSON} Placeholder</a>
      as an example API. The dynamic composables <code>$jsonPlaceholder</code> and <code>useJsonPlaceholderData</code> are generated by the module.
    </p>
  </header>

  <main>
    <NuxtPage />
  </main>
</template>
