<template>
  <Head>
    <Title>nuxt-api-party</Title>
    <Link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css" />
  </Head>

  <header>
    <NuxtLink to="/">
      <h1>nuxt-api-party</h1>
    </NuxtLink>
    <p>
      Requests are proxied by a Nuxt server route and passed back to the client.
      The playground uses <a href="https://jsonplaceholder.typicode.com/">JSON Placeholder</a>
      and <a href="https://petstore3.swagger.io/">Swagger Pet Store</a> as example APIs.
      The dynamic composables <code>$jsonPlaceholder</code> and <code>useJsonPlaceholderData</code>
      are generated by the module.
    </p>
  </header>

  <main>
    <NuxtPage />
  </main>
</template>
